#!flowproc
#
# Generate the reconfigurable module
#

# get data from outside this script
set CHIP_BASE       "$env(CHIP_BASE)"
set RECONF_BASE     "$env(RECONF_BASE)"
set CELLLIB_BASE    "$env(CELLLIB_BASE)"
set CELLLIB_FILE    "$env(CELLLIB_FILE)"
set CELLLIB_MAPS    "$env(CELLLIB_MAPS)"
set APPS_BASE       "$env(APPS_BASE)"
set INTERSYNTH_FILE "$env(INTERSYNTH_FILE)"

# functions
source $CHIP_BASE/chll/functions.tcl

# setup whole reconf.module
source $RECONF_BASE/chll/scripts/setup-reconf-module.tcl
# setup cell library
source $RECONF_BASE/chll/scripts/setup-celllib.tcl
# read TR-FSM wrapper cells using this auto-generated script by
# setup-trfsms.tcl invoked by "flowcmd insert-trfsms"
source $RECONF_BASE/chll/out/setup-trfsm-cells.tcl
# setup example applications
source $RECONF_BASE/chll/scripts/setup-exapps.tcl

puts ""
puts "################################################################################"
puts "## Reading InterSynth results"
read_intersynth -commands "$RECONF_BASE/chll/out/presilicon-baseconfig.txt"
read_intersynth -commands "$RECONF_BASE/chll/out/presilicon-cellmapping.txt"
read_intersynth -commands "$RECONF_BASE/chll/out/presilicon-cellmapping-instances.txt"   ;# not really InterSynth but generated by gen-cellmapping.tcl

read_intersynth -check

# read list of TRFSMs (in variable $TRFSMShortNames)
source $RECONF_BASE/chll/out/trfsm-cells.tcl

#set ExApps "ADT7310"   ;# TODO: remove
set PHASE "presilicon"
foreach App $ExApps {
  set APP_NAME    "$App"
  set AppLC       [string tolower "$App"]
  set AppBase     "${APPS_BASE}/$AppLC"
  set OutDir      "$AppBase/chll/out"
  set ILangFile   "$OutDir/${AppLC}-extract-intersynth-trfsm.il"

  source "$AppBase/chll/scripts/setup.tcl"
  source "$AppBase/chll/scripts/read-netlist.tcl"
  source "$AppBase/chll/scripts/read-intersynth.tcl"
  puts ""
}

puts ""
puts "################################################################################"
puts "## Generating Reconfigurable Module"

puts "## Finishing Reconfigurable Module"

finish_reconf_module

puts "## Writing HDL Code of the Reconfigurable Module"

create_reconf_module_netlist -intersynth

write_netlist -reconfmodule -verilog -module       "$UNIT_BASE/chll/out/reconflogic.v"
write_netlist -reconfmodule -vhdl    -module       "$UNIT_BASE/chll/out/reconflogic.vhd"
write_netlist -reconfmodule -vhdl    -architecture "$UNIT_BASE/chll/out/reconflogic-struct-a.vhd"

puts ""
puts "################################################################################"
puts "## Post-processing, generating application wrappers and bitstreams"
puts "################################################################################"
puts ""
set PHASE "presilicon"
foreach App $ExApps {
  set AppLC       [string tolower "$App"]
  set AppBase     "${APPS_BASE}/$AppLC"
  set Script      "$AppBase/chll/scripts/reconf-module-postproc.tcl"
  puts ""
  source $Script
}

puts "## Done."
