#!trfsmgen
#
# Write TR-FSM wrapper modules and meta-information
#
# This script is sourced by insert-trfsms.tcl.
#

# write TR-FSM wrapper modules
puts "## Writing TR-FSM wrapper modules"
for {set Idx 0} {$Idx < [llength $TRFSMs]} {incr Idx} {
  set Wrapper     [lindex $Wrappers $Idx]
  set ShortName   [lindex $TRFSMShortNames $Idx]
  set ShortNameLC [string tolower $ShortName]
  # write to file
  write_trfsm_wrapper $Wrapper -format vhdl  "$UNIT_OUT_BASE/${ShortNameLC}-wrapper.vhd"
  write_trfsm_wrapper $Wrapper -format ilang "$UNIT_OUT_BASE/${ShortNameLC}-wrapper.il"
}

# create TR-FSM cell information
puts "## Writing script with TR-FSM cell information"
set of [open "${UNIT_OUT_BASE}/trfsm-cells.tcl" "w"]
puts $of "#!tcl"
puts $of "#"
puts $of "# Information on the TR-FSM cells"
puts $of "#"
puts $of "# Auto-generated by [info script]"
puts $of "#"
puts $of ""
puts -nonewline $of "set TRFSMShortNames \[list "
foreach TRFSM $TRFSMShortNames {
  puts -nonewline $of "\"$TRFSM\" "
}
puts $of "\]"
close $of

# create TR-FSM cell information for flowproc
puts "## Writing scripts with TR-FSM cell and wrapper information for flow"
set of [open "${UNIT_OUT_BASE}/setup-trfsm-cells.tcl" "w"]
puts $of "#!flow"
puts $of "#"
puts $of "# Setup all TR-FSM cells"
puts $of "#"
puts $of "# Auto-generated by [info script]"
puts $of "#"
for {set Idx 0} {$Idx < [llength $TRFSMs]} {incr Idx} {
  set TRFSM       [lindex $TRFSMs          $Idx]
  set ShortName   [lindex $TRFSMShortNames $Idx]
  set ShortNameLC [string tolower $ShortName]
  set Wrapper     [lindex $Wrappers        $Idx]
  set ILangFile   "${UNIT_OUT_BASE}/${ShortNameLC}-wrapper.il"
  set TCLFile     "${UNIT_OUT_BASE}/setup-${ShortNameLC}-wrapper.tcl"

  # write setup script of TR-FSM wrapper cell
  write_trfsm_wrapper $Wrapper -format flowtcl "$TCLFile"
  # continue writing to setup-trfsms.tcl
  puts $of ""
  puts $of "# Setup $ShortName"
  puts $of "source $TCLFile"
  puts $of "#puts \"## Reading and checking synthesized netlist $ILangFile\""
  puts $of "#cell_read_netlist \"$ILangFile\""
}
close $of

