#!flowproc
#
# Check InterSynth result
#

# get data from outside this script
set CHIP_BASE       "$env(CHIP_BASE)"
set APP_NAME        "$env(APP_NAME)"
set APP_NAME_LC     "$env(APP_NAME_LC)"
set APP_ILANG_OUT   "$env(APP_ILANG_OUT)"
set APP_OUT_DIR     "$env(APP_OUT_DIR)"
set APP_BASE        "$env(APP_BASE)"
set RECONF_BASE     "$env(RECONF_BASE)"
set CELLLIB_BASE    "$env(CELLLIB_BASE)"

# functions
source $CHIP_BASE/chll/functions.tcl

# setup whole reconf.module
source $RECONF_BASE/chll/scripts/setup-reconf-module.tcl
# setup cell library
source $RECONF_BASE/chll/scripts/setup-celllib.tcl
# read TR-FSM wrapper cells using this auto-generated script by
# setup-trfsms.tcl invoked by "flowcmd insert-trfsms"
source $RECONF_BASE/chll/out/setup-trfsm-cells.tcl
# setup example applications
source $RECONF_BASE/chll/scripts/setup-exapps.tcl

puts ""
puts "################################################################################"
puts "## Reading InterSynth results"
read_intersynth -commands "$RECONF_BASE/chll/out/presilicon-baseconfig.txt"
read_intersynth -commands "$RECONF_BASE/chll/out/presilicon-cellmapping.txt"
read_intersynth -commands "$RECONF_BASE/chll/out/presilicon-cellmapping-instances.txt"   ;# not really InterSynth but generated by gen-cellmapping.tcl

set App         [lindex $ExApps 0]   ;# use first defined Ex.App for reference
set AppLC       [string tolower "$App"]
set APP_NAME    "$App"
set AppBase     "$APP_BASE/../$AppLC"
set OutDir      "$AppBase/chll/out"
set ILangFile   "$OutDir/${AppLC}-extract-intersynth-trfsm.il"
set PHASE       "presilicon"
puts ""
puts "################################################################################"
puts "## Reading Ex.App. $App InterSynth Results for Reference"
source "$AppBase/chll/scripts/setup.tcl"            ;# Required variables: $APP_NAME
source "$AppBase/chll/scripts/read-netlist.tcl"     ;# Required variables: $App, $IlangFile
source "$AppBase/chll/scripts/read-intersynth.tcl"  ;# Required variables: $App, $AppLC, $OutDir, $PHASE
# restore old values
set APP_NAME "$env(APP_NAME)"
unset App AppLC OutDir ILangFile PHASE

# read list of TRFSMs (in variable $TRFSMShortNames)
source $RECONF_BASE/chll/out/trfsm-cells.tcl

puts ""
puts "################################################################################"
puts "## Post-processing, generating application wrappers and bitstreams"
puts "################################################################################"
puts ""
set PHASE "postsilicon"
set App         "$APP_NAME"
set AppLC       "$APP_NAME_LC"
set AppBase     "$APP_BASE"
set Script      "$AppBase/chll/scripts/intersynth-postproc.tcl"
source $Script

puts ""
puts "################################################################################"
puts "## Generating Reconfigurable Module"
finish_reconf_module
create_reconf_module_netlist -intersynth
puts ""

set Script      "$AppBase/chll/scripts/reconf-module-postproc.tcl"
source $Script

puts ""
puts "################################################################################"
puts "## InterSynth Result"
read_intersynth -showinfo
puts ""
puts "See also:"
puts "  HTML Interconnect:  $APP_OUT_DIR/postsilicon.html"
puts "  TikZ tree images:   $APP_OUT_DIR/postsilicon-trees-$APP_NAME_LC.pdf"
puts "  Dot netlist images: $APP_OUT_DIR/postsilicon-netlist-$APP_NAME_LC.svg"
puts ""

puts "## Done."
