
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[13]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[6]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_addr[7]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[1]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[12]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_addr[2]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_addr[9]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[8]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_addr[6]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[5]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_addr[0]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[10]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[3]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[15]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_wen[0]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_addr[11]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_addr[3]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[2]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[0]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[11]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[7]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_addr[4]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[4]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[9]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_addr[1]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_dout[14]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_addr[10]}]
set_property MARK_DEBUG true [get_nets core_1/PMem_0/ram_cen]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_wen[1]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_addr[8]}]
set_property MARK_DEBUG true [get_nets {core_1/PMem_0/ram_addr[5]}]
set_property MARK_DEBUG true [get_nets core_1/openMSP430_0/dbg_i2c_sda_in]
set_property MARK_DEBUG true [get_nets core_1/openMSP430_0/dbg_i2c_sda_out]
set_property MARK_DEBUG true [get_nets core_1/openMSP430_0/dbg_i2c_scl]
set_property MARK_DEBUG true [get_nets core_1/spi_master_1/MISO_i]
set_property MARK_DEBUG true [get_nets core_1/spi_master_1/SCK_o]
set_property MARK_DEBUG true [get_nets core_1/spi_master_1/Transmission_o]
set_property MARK_DEBUG true [get_nets core_1/spi_master_1/MOSI_o]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[14]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[3]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[8]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[2]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[15]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[7]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[6]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[1]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[13]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[5]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[10]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[11]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[0]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[12]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[4]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[9]}]
set_property MARK_DEBUG true [get_nets core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113/Clk_i]
set_property MARK_DEBUG true [get_nets core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113/Preset_i]
set_property MARK_DEBUG true [get_nets core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113/Zero_o]
set_property MARK_DEBUG true [get_nets core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113/Enable_i]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_i[0]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_o[2]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_i[1]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Output_o[0]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_i[2]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Input_i[0]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_o[3]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/State_o[0]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Output_o[4]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Input_i[3]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Input_i[1]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Input_i[2]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_i[3]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_o[0]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Input_i[4]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/State_o[1]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Output_o[3]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/State_o[3]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Output_o[1]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_o[1]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/State_o[2]}]
set_property MARK_DEBUG true [get_nets {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Output_o[2]}]

create_debug_core u_ila_0_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0_0]
set_property port_width 1 [get_debug_ports u_ila_0_0/clk]
connect_debug_port u_ila_0_0/clk [get_nets [list Clk_i_IBUF_BUFG]]
set_property port_width 2 [get_debug_ports u_ila_0_0/probe0]
connect_debug_port u_ila_0_0/probe0 [get_nets [list {core_1/PMem_0/ram_wen[0]} {core_1/PMem_0/ram_wen[1]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 16 [get_debug_ports u_ila_0_0/probe1]
connect_debug_port u_ila_0_0/probe1 [get_nets [list {core_1/PMem_0/ram_dout[0]} {core_1/PMem_0/ram_dout[1]} {core_1/PMem_0/ram_dout[2]} {core_1/PMem_0/ram_dout[3]} {core_1/PMem_0/ram_dout[4]} {core_1/PMem_0/ram_dout[5]} {core_1/PMem_0/ram_dout[6]} {core_1/PMem_0/ram_dout[7]} {core_1/PMem_0/ram_dout[8]} {core_1/PMem_0/ram_dout[9]} {core_1/PMem_0/ram_dout[10]} {core_1/PMem_0/ram_dout[11]} {core_1/PMem_0/ram_dout[12]} {core_1/PMem_0/ram_dout[13]} {core_1/PMem_0/ram_dout[14]} {core_1/PMem_0/ram_dout[15]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 12 [get_debug_ports u_ila_0_0/probe2]
connect_debug_port u_ila_0_0/probe2 [get_nets [list {core_1/PMem_0/ram_addr[0]} {core_1/PMem_0/ram_addr[1]} {core_1/PMem_0/ram_addr[2]} {core_1/PMem_0/ram_addr[3]} {core_1/PMem_0/ram_addr[4]} {core_1/PMem_0/ram_addr[5]} {core_1/PMem_0/ram_addr[6]} {core_1/PMem_0/ram_addr[7]} {core_1/PMem_0/ram_addr[8]} {core_1/PMem_0/ram_addr[9]} {core_1/PMem_0/ram_addr[10]} {core_1/PMem_0/ram_addr[11]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 16 [get_debug_ports u_ila_0_0/probe3]
connect_debug_port u_ila_0_0/probe3 [get_nets [list {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[0]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[1]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[2]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[3]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[4]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[5]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[6]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[7]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[8]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[9]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[10]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[11]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[12]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[13]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[14]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113_5[15]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 5 [get_debug_ports u_ila_0_0/probe4]
connect_debug_port u_ila_0_0/probe4 [get_nets [list {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Input_i[0]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Input_i[1]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Input_i[2]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Input_i[3]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Input_i[4]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 4 [get_debug_ports u_ila_0_0/probe5]
connect_debug_port u_ila_0_0/probe5 [get_nets [list {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_o[0]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_o[1]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_o[2]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_o[3]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 4 [get_debug_ports u_ila_0_0/probe6]
connect_debug_port u_ila_0_0/probe6 [get_nets [list {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_i[0]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_i[1]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_i[2]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/NextState_i[3]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 5 [get_debug_ports u_ila_0_0/probe7]
connect_debug_port u_ila_0_0/probe7 [get_nets [list {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Output_o[0]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Output_o[1]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Output_o[2]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Output_o[3]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/Output_o[4]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 4 [get_debug_ports u_ila_0_0/probe8]
connect_debug_port u_ila_0_0/probe8 [get_nets [list {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/State_o[0]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/State_o[1]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/State_o[2]} {core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_126/TRFSM_1/State_o[3]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe9]
connect_debug_port u_ila_0_0/probe9 [get_nets [list core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113/Clk_i]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe10]
connect_debug_port u_ila_0_0/probe10 [get_nets [list core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113/Enable_i]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe11]
connect_debug_port u_ila_0_0/probe11 [get_nets [list core_1/spi_master_1/MISO_i]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe12]
connect_debug_port u_ila_0_0/probe12 [get_nets [list core_1/spi_master_1/MOSI_o]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe13]
connect_debug_port u_ila_0_0/probe13 [get_nets [list core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113/Preset_i]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe14]
connect_debug_port u_ila_0_0/probe14 [get_nets [list core_1/PMem_0/ram_cen]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe15]
connect_debug_port u_ila_0_0/probe15 [get_nets [list core_1/spi_master_1/SCK_o]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe16]
connect_debug_port u_ila_0_0/probe16 [get_nets [list core_1/spi_master_1/Transmission_o]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe17]
connect_debug_port u_ila_0_0/probe17 [get_nets [list core_1/MyReconfigLogic_0/MyInterSynthModule_0/cell_113/Zero_o]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets Clk_i_IBUF_BUFG]
