#!flowproc
#
# Check InterSynth result
#

# get data from outside this script
set CHIP_BASE       "$env(CHIP_BASE)"
set RECONF_BASE     "$env(RECONF_BASE)"
set CELLLIB_BASE    "$env(CELLLIB_BASE)"
set CELLLIB_FILE    "$env(CELLLIB_FILE)"
set CELLLIB_MAPS    "$env(CELLLIB_MAPS)"
set APPS_BASE       "$env(APPS_BASE)"
set INTERSYNTH_FILE "$env(INTERSYNTH_FILE)"

# functions
source $CHIP_BASE/chll/functions.tcl

# setup whole reconf.module
source $RECONF_BASE/chll/scripts/setup-reconf-module.tcl
# setup cell library
source $RECONF_BASE/chll/scripts/setup-celllib.tcl
# read TR-FSM wrapper cells using this auto-generated script by
# setup-trfsms.tcl invoked by "flowcmd insert-trfsms"
source $RECONF_BASE/chll/out/setup-trfsm-cells.tcl
# setup example applications
source $RECONF_BASE/chll/scripts/setup-exapps.tcl

puts ""
puts "################################################################################"
puts "## Reading InterSynth results"
read_intersynth -commands "$RECONF_BASE/chll/out/presilicon-baseconfig.txt"
read_intersynth -commands "$RECONF_BASE/chll/out/presilicon-cellmapping.txt"
read_intersynth -commands "$RECONF_BASE/chll/out/presilicon-cellmapping-instances.txt"   ;# not really InterSynth but generated by gen-cellmapping.tcl

read_intersynth -check

# read list of TRFSMs (in variable $TRFSMShortNames)
source $RECONF_BASE/chll/out/trfsm-cells.tcl

puts ""
puts "################################################################################"
puts "## Post-processing, generating application wrappers and bitstreams"
puts "################################################################################"
puts ""
set PHASE "presilicon"
foreach App $ExApps {
  set AppLC       [string tolower "$App"]
  set AppBase     "${APPS_BASE}/$AppLC"
  set Script      "$AppBase/chll/scripts/intersynth-postproc.tcl"
  puts ""
  source $Script
}

puts ""
puts "################################################################################"
puts "## InterSynth Result"
set StatsFile "$RECONF_BASE/chll/out/intersynth-stats.txt"
puts ""
puts "InterSynth Statistics ($StatsFile):"
set handle [open "$StatsFile" r]
puts [read $handle]
close $handle
puts ""
read_intersynth -showinfo
puts ""
puts "See also:"
puts "  HTML Interconnect:  $RECONF_BASE/chll/out/presilicon.html"
puts "  TikZ tree images:   ${APPS_BASE}/*/chll/out/presilicon-trees-*.pdf"
puts "  Dot netlist images: ${APPS_BASE}/*/chll/out/presilicon-netlist-*.svg"
puts ""

puts "## Done."
