#!tcl
#
# Use presilicon.tcl to generate cellmapping with instance information
#

# get data from command line

if {$argc != 1} {
  puts "Usage: $argv0 script"
  exit 1
}

set SCRIPT [lindex $argv 0]

proc intersynth_cell {instance_name cell_type cell_num} {
  puts "mapinstance $cell_type $cell_num $instance_name"
}

proc intersynth_path_cell {instance_name cell_type input_names output_names} {
  # do nothing
}

proc intersynth_path_conn {connection_type> instance_outputs_pair input_ports instance_inputs_pair output_ports} {
  # do nothing
}

puts "# generated by [info script]"
source "$SCRIPT"
