#!tclsh
#
# Generate SDC timing constraints (more precisely: timing exceptions) for the
# interconnect, which is automatically generated by InterSynth, to break the
# combinational loops.
#
# This script is unused because a different approach to break the combinational
# loops was used. See ../../../../doc/synthesis/dc-break-loops.tcl.
#

set max_delay_cells_default     25.0
set max_delay_conntypes_default 25.0

set f stdout

puts $f "set INTERSYNTH_PATH \"core_1/MyReconfigLogic_0/MyInterSynthModule_0/\""

puts $f "##############################################################################"
puts $f "# Delay values"
puts $f "##############################################################################"

array set celltypes {}

proc intersynth_cell {cell type num} {
}
proc intersynth_path_cell {cell type inputs outputs} {
  global f
  global celltypes
  if {[llength [array get celltypes "$type"]] != 0} {
    return
  }

  set celltypes($type) 1
  puts $f ""
  puts $f "# Delay values for cell type $type"
  puts $f "set max_delay_$type     \$max_delay_cells_default     ;# abbreviation so that all in->out paths have the same delay"
  foreach in $inputs {
    foreach out $outputs {
      puts $f "set max_delay_${type}_${in}_${out}\    \$max_delay_$type"
    }
  }
}
proc intersynth_path_conn {conn from_cells from_ports to_cells to_ports} {
  global f
  puts $f ""
  puts $f "# Delay value for connection type $conn"
  puts $f "set max_delay_${conn}     \$max_delay_conntypes_default"
}

puts $f "set max_delay_cells_default     $max_delay_cells_default"
puts $f "set max_delay_conntypes_default $max_delay_conntypes_default"
source ../out/presilicon.tcl

puts $f "##############################################################################"
puts $f "# Set missing delay values"
puts $f "##############################################################################"

array unset celltypes {*}

proc intersynth_cell {cell type num} {
}
proc intersynth_path_cell {cell type inputs outputs} {
  global f
  global celltypes
  if {[llength [array get celltypes "$type"]] != 0} {
    return
  }

  set celltypes($type) 1
  puts $f ""
  puts $f "# Default delay values for cell type $type"
  foreach in $inputs {
    foreach out $outputs {
      puts $f "if \{ !\[ info exists max_delay_${type}_${in}_${out} \] \} \{ set max_delay_${type}_${in}_${out}    \$max_delay_cells_default \}"
    }
  }
}
proc intersynth_path_conn {conn from_cells from_ports to_cells to_ports} {
  global f
  puts $f ""
  puts $f "# Delay value for connection type $conn"
#  puts $f "if \{ !\[ info exists max_delay_${conn} \] \} \{ set max_delay_${conn}    \$max_delay_conntypes_default \}"
}

puts $f "set max_delay_cells_default     $max_delay_cells_default"
puts $f "set max_delay_conntypes_default $max_delay_conntypes_default"
source ../out/presilicon.tcl

puts $f "##############################################################################"
puts $f "# Constraints"
puts $f "##############################################################################"

set intersynth_cell_count 0
set intersynth_path_cell_count 0
set intersynth_path_conn_count 0

proc intersynth_cell {cell type num} {
  global f
  global intersynth_cell_count
  if {$intersynth_cell_count == 0} {
    puts $f "# disable timing arcs through all cells"
  }
  incr intersynth_cell_count

  puts $f "set_disable_timing \[get_cells \$\{INTERSYNTH_PATH\}$cell\]"
}

proc intersynth_path_cell {cell type inputs outputs} {
  global f
  global intersynth_path_cell_count
  if {$intersynth_path_cell_count == 0} {
    puts $f ""
    puts $f "# constrain propagation delay for all cells"
  }
  incr intersynth_path_cell_count

  foreach in $inputs {
    foreach out $outputs {
      puts $f "set_max_delay -from \"\$\{INTERSYNTH_PATH\}$cell/$in\" -to \"\$\{INTERSYNTH_PATH\}$cell/$out\" \$\{max_delay_${type}_${in}_${out}\}"
    }
  }
}

proc intersynth_path_conn {conn from_cells from_ports to_cells to_ports} {
  global f
  global intersynth_path_conn_count
  if {$intersynth_path_conn_count == 0} {
    puts $f ""
    puts $f "# constrain propagation delay of interconnects"
  }
  incr intersynth_path_conn_count

  set cmd "set_max_delay -from \""
  set spacer ""
  foreach {cell ports} $from_cells {
    foreach port $ports {
      set cmd "$cmd$spacer$\{INTERSYNTH_PATH\}$cell/$port"
      set spacer " "
    }
  }
  foreach port $from_ports {
    set cmd "$cmd$spacer$\{INTERSYNTH_PATH\}$port"
    set spacer " "
  }
  set cmd "$cmd\" -to \""
  set spacer ""
  foreach {cell ports} $to_cells {
    foreach port $ports {
      set cmd "$cmd$spacer$\{INTERSYNTH_PATH\}$cell/$port"
      set spacer " "
    }
  }
  foreach port $to_ports {
    set cmd "$cmd$spacer$\{INTERSYNTH_PATH\}$port"
    set spacer " "
  }
  set cmd "$cmd\" \$\{max_delay_$conn\}"
  puts $f $cmd

  set cmd "set_max_delay -to \""
#  set cmd "set_max_delay -from \""
#  set spacer ""
#  foreach port $to_ports {
#    set cmd "$cmd$spacer$\{INTERSYNTH_PATH\}$port"
#    set spacer " "
#  }
#  set cmd "$cmd\" -to \""
  set spacer ""
  foreach port $from_ports {
    set cmd "$cmd$spacer$\{INTERSYNTH_PATH\}$port"
    set spacer " "
  }
  set cmd "$cmd\" \$\{max_delay_$conn\}"
  puts $f $cmd

}

source ../out/presilicon.tcl

puts $f ""
puts $f "# Generated constraints for $intersynth_cell_count cells and $intersynth_path_conn_count interconnects"
