#!flowproc
#
# Check synthesized application netlist
#

# get data from outside this script
set APP_NAME      "$env(APP_NAME)"
set APP_NAME_LC   "$env(APP_NAME_LC)"
set APP_ILANG_OUT "$env(APP_ILANG_OUT)"
set RECONF_BASE   "$env(RECONF_BASE)"
set CELLLIB_BASE  "$env(CELLLIB_BASE)"

# setup whole reconf.module
source $RECONF_BASE/chll/scripts/setup-reconf-module.tcl
# setup cell library
source $RECONF_BASE/chll/scripts/setup-celllib.tcl
# read TR-FSM wrapper cells using this auto-generated script by
# setup-trfsms.tcl invoked by "flowcmd insert-trfsms"
source $RECONF_BASE/chll/out/setup-trfsm-cells.tcl
# setup example applications
source $RECONF_BASE/chll/scripts/setup-exapps.tcl

puts ""
puts "################################################################################"
puts "## Reading InterSynth results"
read_intersynth -commands "$RECONF_BASE/chll/out/presilicon-baseconfig.txt"
read_intersynth -commands "$RECONF_BASE/chll/out/presilicon-cellmapping.txt"
read_intersynth -commands "$RECONF_BASE/chll/out/presilicon-cellmapping-instances.txt"   ;# not really InterSynth but generated by gen-cellmapping.tcl

read_intersynth -check

# read list of TRFSMs (in variable $TRFSMShortNames)
source $RECONF_BASE/chll/out/trfsm-cells.tcl

# setup application
set SCRIPT_BASE [file dirname [info script]]
source $SCRIPT_BASE/setup.tcl

# print information to the screen
app_show

# Read and check synthesized netlist
puts "## Reading and checking synthesized netlist $APP_ILANG_OUT"
set IgnoreList [list "\$fsm"]
app_read_netlist -extracted -ignore $IgnoreList -post-si $APP_ILANG_OUT

puts "## Done."

puts ""

# show all cell instances
puts ""
puts "##############################################################################################"
puts "## Resources #################################################################################"
puts "##############################################################################################"
puts ""
read_intersynth -showinfo   ;# also shows the app. usage
puts ""
puts "##############################################################################################"

puts "## Done."
